name: C Project Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Run tests
      run: |
        git submodule update -i
        chmod +x ./combination_test/run_test.sh
        ./combination_test/run_test.sh
